"""Assemble a markdown onboarding report for juniors."""

from __future__ import annotations

from datetime import datetime, timezone


def render_report(scout: dict, architect: dict, teacher: dict) -> str:
    stack = scout.get("stack", {})
    docs = scout.get("docs", {})
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    mode = "LLM-assisted" if teacher.get("used_llm") else "offline heuristic"

    lines: list[str] = [
        f"# Junior Onboarding Guide: `{scout.get('repo_name')}`",
        "",
        f"_Generated by Repo Explainer Agent ({mode}) on {generated}_",
        "",
        "## What is this project?",
        "",
        teacher.get("plain_summary", "").strip(),
        "",
        "## Welcome note",
        "",
        teacher.get("pep_talk", "").strip(),
        "",
        "## Tech stack at a glance",
        "",
        f"- **Primary language:** {stack.get('primary_language', 'Unknown')}",
        f"- **Languages:** {', '.join(stack.get('languages') or ['Unknown'])}",
        f"- **Frameworks / libraries:** {', '.join(stack.get('frameworks') or ['none detected'])}",
        f"- **Package managers:** {', '.join(stack.get('package_managers') or ['none detected'])}",
        f"- **Tooling:** {', '.join(stack.get('tooling') or ['none detected'])}",
        f"- **Has tests:** {'yes' if stack.get('has_tests') else 'not clearly detected'}",
        "",
        "## Folder map (start here)",
        "",
        "```text",
        scout.get("tree", "(empty)"),
        "```",
        "",
        "## What each top-level piece is for",
        "",
    ]

    for module in architect.get("modules", []):
        kind = "dir" if module["kind"] == "directory" else "file"
        lines.append(f"- `{module['name']}` ({kind}): {module['role']}")

    lines.extend(
        [
            "",
            "## Mental model",
            "",
            architect.get("mental_model", ""),
            "",
            "## How a run typically flows",
            "",
        ]
    )
    for i, step in enumerate(architect.get("data_flow", []), start=1):
        lines.append(f"{i}. {step}")

    lines.extend(["", "## Suggested learning path", ""])
    for item in teacher.get("learning_path", []):
        lines.append(f"### Step {item['step']}: {item['title']}")
        lines.append("")
        lines.append(f"- **Why:** {item['why']}")
        lines.append(f"- **Do:** {item['do']}")
        lines.append("")

    lines.extend(["", "## Quick-start hints from the repo", ""])
    for hint in docs.get("quick_start_hints") or ["No automated hints found."]:
        lines.append(f"- {hint}")

    if architect.get("entry_points"):
        lines.extend(["", "## Likely entry points", ""])
        for ep in architect["entry_points"]:
            lines.append(f"- `{ep}`")

    if architect.get("file_sketches"):
        lines.extend(["", "## Sample file sketches", ""])
        for sketch in architect["file_sketches"]:
            lines.append(f"- {sketch['sketch']}")

    lines.extend(["", "## Glossary", ""])
    for term in teacher.get("glossary", []):
        lines.append(f"- **{term['term']}:** {term['meaning']}")

    lines.extend(["", "## Common junior pitfalls", ""])
    for pitfall in teacher.get("common_pitfalls", []):
        lines.append(f"- {pitfall}")

    lines.extend(["", "## First-week plan", ""])
    for day in teacher.get("first_week_plan", []):
        lines.append(f"- {day}")

    lines.extend(
        [
            "",
            "---",
            "",
            "Tip: keep this guide next to the repo and update it as you learn. "
            "Teaching someone else is the fastest way to lock the map into memory.",
            "",
        ]
    )
    return "\n".join(lines)
